<script>
    import { onMount } from 'svelte';

//let data

//onMount(async () => {
//  const response = await fetch('https://rickandmortyapi.com/api/character/1,2,3')
//  data = await response.json()
//  console.log(data)
//})

//let res

const fetchData = async () => {
  return fetch('https://jsonplaceholder.typicode.com/users/1/posts')
  .then(res => {
    if (res.ok) {
      console.log('SUCCESS')
      return res.json()
    } else {
      console.log('UNSUCCESSFUL')
    }
  })
//  .then(res => res)
  .catch(e => console.error(e))
}

let d = fetchData()

const fetchRickMorty = async () => {
  return fetch('https://rickandmortyapi.com/api/character/')
  .then(response => response.json())
  //.then(response => response)
  .catch(e => console.error(e))
}
let data
function alert() {
  data = fetchRickMorty()
  console.log(data)
}


//async function getChar() {
//    const response2 = await fetch('https://rickandmortyapi.com/api/character/1,2,3,4,5,6')
//    individuals = await response2.json()
//    console.log(individuals)
//    if (response2.ok) {
//      return individuals
//    } else {
//      throw new Error(individuals)
//    }
//};


</script>

<main class="p-5">
<div class="text-center"><button on:click|once={alert}>Click here</button></div>
<ul>

  {#if data}
  {#await data}
  Loading data...
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="44px" height="44px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <circle cx="30" cy="50" fill="#e90c59" r="20">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="-0.5s"></animate>
    </circle>
    <circle cx="70" cy="50" fill="#46dff0" r="20">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="0s"></animate>
    </circle>
    <circle cx="30" cy="50" fill="#e90c59" r="20">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="-0.5s"></animate>
      <animate attributeName="fill-opacity" values="0;0;1;1" calcMode="discrete" keyTimes="0;0.499;0.5;1" dur="1s" repeatCount="indefinite"></animate>
    </circle>
    <!-- [ldio] generated by https://loading.io/ --></svg>
  {:then data}
    {#each data.results as item}
    {item.id} + {item.name} + {item.status}<br>
    <img src={item.image} alt={item.name}><br><br>
    {/each}
  {/await}
  {:else}
    Click the button!
  {/if}

  <div class="h-10 bg-red-300"></div>
  {#await d}
  Loading.. 
  <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgb(255, 255, 255); display: block; shape-rendering: auto;" width="44px" height="44px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
    <circle cx="30" cy="50" fill="#e90c59" r="20">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="-0.5s"></animate>
    </circle>
    <circle cx="70" cy="50" fill="#46dff0" r="20">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="0s"></animate>
    </circle>
    <circle cx="30" cy="50" fill="#e90c59" r="20">
      <animate attributeName="cx" repeatCount="indefinite" dur="1s" keyTimes="0;0.5;1" values="30;70;30" begin="-0.5s"></animate>
      <animate attributeName="fill-opacity" values="0;0;1;1" calcMode="discrete" keyTimes="0;0.499;0.5;1" dur="1s" repeatCount="indefinite"></animate>
    </circle>
    <!-- [ldio] generated by https://loading.io/ --></svg>
  {:then d}
    {#each d as post}
        {post.id}.....{post.userId}<br>
        {post.title}<br>
        -----------------------<br>
    {/each}
  {/await}

  
  <!--
<hr>
{#if data}
  {#each data as individual}
  <p>{individual.id} - {individual.name}</p>
  <p><img src={individual.image} alt={individual.name}></p>
  {/each}
{:else}
<p>loading...</p>
{/if}
-->
</ul>

</main>